apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ansible-smells-cert
  namespace: sodalite-services
spec:
  commonName: ansible-smells.public-testbed.sodalite.eu
  secretName: ansible-smells-cert
  dnsNames:
    - ansible-smells.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
