apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ruleserver-cert
  namespace: sodalite-services
spec:
  commonName: ruleserver.public-testbed.sodalite.eu
  secretName: ruleserver-cert
  dnsNames:
    - ruleserver.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
