apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruleserver
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: ruleserver
  replicas: 1
  template:
    metadata:
      labels:
        app: ruleserver
    spec:
      containers:
      - image: sodaliteh2020/monitoring-system-ruleserver
        name: ruleserver
        env:
        - name: GUNICORN_WORKERS
          value: "4"
        - name: RULESERVER_PORT
          value: "9092"
        ports:
        - containerPort: 9092
          protocol: TCP
        volumeMounts:
        - name: prometheus-rules
          mountPath: /etc/prometheus/rules/
          subPath: rules
      volumes:
      - name: prometheus-rules
        persistentVolumeClaim:
          claimName: prometheus-rules