apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: sodalite-services
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - alertmanager:9093

    rule_files:
      - /etc/prometheus/rules/*

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'consul-registered-node-exporters'
        consul_sd_configs:
          - server: consul:8500
            services: [consul-registered-node-exporters]

      - job_name: 'hpc-exporter'
        scrape_interval: 5s
        static_configs:
          - targets: ['hpc-exporter:9110']

      - job_name: 'consul-registered-skydive-exporters'
        consul_sd_configs:
          - server: consul:8500
            services: [consul-registered-skydive-exporters]
