apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.23.0
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP