apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus
  namespace: sodalite-services
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: sodalite-services
  labels:
    app: prometheus
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: prometheus
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
!    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
!        - key: kubernetes.io/hostname
          operator: In
          values:
!          - example-node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: sodalite-services
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: prometheus