---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:7.3.7
        name: grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-pw
        - name: GF_GENERIC_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-id
        - name: GF_GENERIC_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-secret
        - name: GF_GENERIC_OAUTH_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: auth-url
        - name: GF_GENERIC_OAUTH_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: token-url
        - name: GF_GENERIC_OAUTH_API_URL
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: api-url
        - name: GF_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
          valueFrom:
            secretKeyRef:
              name: grafana
              key: role-attribute-path
        - name: GF_USERS_ALLOW_SIGN_UP
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_USERS_ALLOW_SIGN_UP
        - name: GF_USERS_DISABLE_LOGIN_FORM
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_USERS_DISABLE_LOGIN_FORM      
        - name: GF_USERS_OAUTH_AUTO_LOGIN
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_USERS_OAUTH_AUTO_LOGIN     
        - name: GF_USERS_SIGNOUT_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_USERS_SIGNOUT_REDIRECT_URL     
        - name: GF_GENERIC_OAUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_GENERIC_OAUTH_ENABLED     
        - name: GF_GENERIC_OAUTH_ALLOW_SIGN_UP
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_GENERIC_OAUTH_ALLOW_SIGN_UP    
        - name: GF_GENERIC_OAUTH_NAME
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_GENERIC_OAUTH_NAME   
        - name: GF_GENERIC_OAUTH_SCOPES
          valueFrom:
            configMapKeyRef:
              name: grafana-registry
              key: GF_GENERIC_OAUTH_SCOPES  
        - name: GF_SERVER_DOMAIN
          value: "grafana.public-testbed.sodalite.eu"
        - name: GF_SERVER_ROOT_URL
          value: "http://grafana.public-testbed.sodalite.eu/"
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
          - name: grafana-dashboards
            mountPath: "/etc/grafana/provisioning/dashboards"
          - name: provisioning
            mountPath: "/etc/grafana/provisioning"
      volumes:
      - name: provisioning
        configMap:
          name: grafana-registry
          items:
            - key: datasources
              path: datasources/datasources.yaml
            - key: dashboards
              path: dashboards/dashboards.yaml
  volumeClaimTemplates:
  - metadata:
      name: grafana-dashboards
      namespace: sodalite-services
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi