apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: sodalite-services
spec:
  serviceName: registry
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: library/registry:2
        name: registry
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
  volumeClaimTemplates:
  - metadata:
      name: registry-storage
      namespace: sodalite-services
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi