apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-discovery-service
spec:
  selector:
    matchLabels:
      app: platform-discovery-service
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-discovery-service
    spec:
      containers:
      - image: sodaliteh2020/platform-discovery-service
        name: platform-discovery-service
        env:
        - name: SECRET_VAULT_LOGIN_URI
          valueFrom:
            configMapKeyRef:
              name: platform-discovery-service
              key: SECRET_VAULT_LOGIN_URI
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: platform-discovery-service
              key: OIDC_INTROSPECTION_ENDPOINT
        - name: SECRET_VAULT_URI
          valueFrom:
            configMapKeyRef:
              name: platform-discovery-service
              key: SECRET_VAULT_URI
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: platform-discovery-service
              key: OIDC_CLIENT_SECRET
        ports:
        - containerPort: 8089
          protocol: TCP