apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    k8s.scw.cloud/ingress: traefik2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 8080
      name: xopera
      targetPort: 8080
    - port: 443
      name: https
      targetPort: 8443
  selector:
    app.kubernetes.io/name: traefik