apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    k8s.scw.cloud/ingress: traefik2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 8080
      name: semantic-web
      targetPort: 8080
    - port: 8081
      name: iac-builder
      targetPort: 8081
    - port: 8500
      name: consul
      targetPort: 8500
    - port: 8600
      name: consul-disco
      targetPort: 8600
    - port: 9090
      name: prometheus
      targetPort: 9090
    - port: 9093
      name: alertmanager
      targetPort: 9093
    - port: 443
      name: https
      targetPort: 8443
  selector:
    app.kubernetes.io/name: traefik