---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: sodalite-services
spec:
  selector:
    app: keycloak-postgres
  ports:
  - port: 5432
    protocol: TCP
    name: postgres