- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    # DIRECTORIES 
    - name: Ensure configuration datasources directory exists
      file:
        path: "{{ dest_conf_datasources | dirname }}"
        state: directory
    - name: Ensure configuration dashboards directory exists
      file:
        path: "{{ dest_conf_dashboards | dirname }}"
        state: directory
    - name: Ensure dashboards directory exists
      file:
        path: "{{ dest_dashboards }}"
        state: directory
    # CONF FILES
    - name: Create datasources configuration file
      template:
        src: "grafana-datasources.yaml.tmpl"
        dest: "{{ dest_conf_datasources }}"
    - name: Create datasources configuration file
      template:
        src: "grafana-dashboards.yaml.tmpl"
        dest: "{{ dest_conf_dashboards }}"
    # DASHBOARDS FILES
    - name: Create 1-SODALITE-EXPORTER Dashboard
      copy:
        src: "dashboard-1-sodalite-exporters.json"
        dest: "{{ dest_dashboards }}/dashboard-1-sodalite-exporters.json"

    - name: Create 2-SODALITE-NODE-EXPORTER Dashboard
      copy:
        src: "dashboard-2-sodalite-node-exporters.json"
        dest: "{{ dest_dashboards }}/dashboard-2-sodalite-node-exporters.json"

    - name: Create 3-SODALITE-SKYDIVE-EXPORTER Dashboard
      copy:
        src: "dashboard-3-sodalite-skydive-exporters.json"
        dest: "{{ dest_dashboards }}/dashboard-3-sodalite-skydive-exporters.json"

    - name: Create 4-SODALITE-HPC-EXPORTER Dashboard 
      copy:
        src: "dashboard-4-sodalite-hpc-exporters.json"
        dest: "{{ dest_dashboards }}/dashboard-4-sodalite-hpc-exporters.json"

    - name: Create 5-SODALITE-IPM-EXPORTER Dashboard 
      copy:
        src: "dashboard-5-sodalite-ipmi-exporters.json"
        dest: "{{ dest_dashboards }}/dashboard-5-sodalite-ipmi-exporters.json"