apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantic-web-ingress
  namespace: sodalite-services
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: semantic-web
            port:
              name: semantic-web