apiVersion: apps/v1
kind: Deployment
metadata:
  name: tosca-smells
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: tosca-smells
  replicas: 1
  template:
    metadata:
      labels:
        app: tosca-smells
    spec:
      containers:
      - image: sodaliteh2020/toscasmells:349
        name: tosca-smells
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: WAIT_HOSTS
          value: knowledge-db.sodalite-services.svc.cluster.local
        - name: environment
          value: docker
        - name: graphdb
          value: http://knowledge-db.sodalite-services.svc.cluster.local:7200/
        - name: reasoner
          value: http://semantic-web.sodalite-services.svc.cluster.local:8080/reasoner-api/v0.6/
        - name: kbUsername
          value: admin
        - name: kbPassword
          valueFrom:
            secretKeyRef:
              name: semantic-web
              key: kb_password
