apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: modak-cert
  namespace: sodalite-services
spec:
  commonName: modak.public-testbed.sodalite.eu
  secretName: modak-cert
  dnsNames:
    - modak.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
