apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-skydive-connector-cert
  namespace: sodalite-services
spec:
  commonName: prometheus-skydive-connector.public-testbed.sodalite.eu
  secretName: prometheus-skydive-connector-cert
  dnsNames:
    - prometheus-skydive-connector.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
