---
apiVersion: v1
kind: Service
metadata:
  name: xopera-rest-api
  namespace: sodalite-services
spec:
  selector:
    app.kubernetes.io/name: xopera-rest-api
  ports:
  - port: 8080
    protocol: TCP
    name: http