{
 "title": "SODALITE-NODE-EXPORTERS",
 "description": "Dashboard for the prometheus node exporters",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment_label",
    "label": "Deployment Label",
    "query": "label_values(node_cpu_seconds_total, group_name)"
   },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": "label_values(node_cpu_seconds_total{group_name=~\"$deployment_label\"}, instance_name)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{group_name=~\"$deployment_label\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview (associated Deployment)，Instance：$instance_name，IP Address：$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overview【Deployment：$deployment_label，Total：$total】",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{group_name=~\"$deployment_label\"})by(instance_name)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"} - 0",
     "legendFormat": "Total memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{group_name=~\"$deployment_label\",mode='system'}) by (instance_name)",
     "legendFormat": "Total #cores"
    },
    {
     "expr": "node_load5{group_name=~\"$deployment_label\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",mode=\"idle\"}[$interval])) by (instance_name)) * 100",
     "legendFormat": "CPU load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{group_name=~\"$deployment_label\"} / (node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"})))* 100",
     "legendFormat": "Memory used"
    },
    {
     "expr": "max((node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{group_name=~\"$deployment_label\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes{group_name=~\"$deployment_label\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{group_name=~\"$deployment_label\",fstype=~\"ext.?|xfs\"})))by(instance_name)",
     "legendFormat": "Disk partition usage"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{group_name=~\"$deployment_label\"}[$interval])) by (instance_name)",
     "legendFormat": "Maximum read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{group_name=~\"$deployment_label\"}[$interval])) by (instance_name)",
     "legendFormat": "Maximum write"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{group_name=~\"$deployment_label\"} - 0",
     "legendFormat": "#connections"
    },
    {
     "expr": "node_sockstat_TCP_tw{group_name=~\"$deployment_label\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{group_name=~\"$deployment_label\"}[$interval])*8) by (instance_name)",
     "legendFormat": "Download bandwidth"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{group_name=~\"$deployment_label\"}[$interval])*8) by (instance_name)",
     "legendFormat": "Upload bandwidth"
    }
   ]
  },
  {
   "title": "$deployment_label：Overall total 5m load & average CPU used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Total 5m load" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{group_name=~\"$deployment_label\", mode='system'})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{group_name=~\"$deployment_label\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "$deployment_label：Overall total memory & average memory used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"} - node_memory_MemAvailable_bytes{group_name=~\"$deployment_label\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"} - node_memory_MemAvailable_bytes{group_name=~\"$deployment_label\"}) / sum(node_memory_MemTotal_bytes{group_name=~\"$deployment_label\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "$deployment_label：Overall total disk & average disk used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name)) - sum(avg(node_filesystem_free_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name)) - sum(avg(node_filesystem_free_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name))) *100/sum(avg(node_filesystem_size_bytes{group_name=~\"$deployment_label\",fstype=~\"xfs|ext.*\"})by(device,instance_name))",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "Resource Details：【$instance_name】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance_name=~\"$instance_name\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance_name=~\"$instance_name\"} / (node_memory_MemTotal_bytes{instance_name=~\"$instance_name\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance_name=~\"$instance_name\"} + 1)/ (node_memory_SwapTotal_bytes{instance_name=~\"$instance_name\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$instance_name】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance_name=~\"$instance_name\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "CPU load per core",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",mode=\"idle\"}[$interval])) by (cpu)) *100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance_name=~\"$instance_name\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance_name=~\"$instance_name\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_name=~\"$instance_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance_name=~\"$instance_name\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",} - node_memory_MemAvailable_bytes{instance_name=~\"$instance_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"} / (node_memory_MemTotal_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/node_filesystem_size_bytes{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "s", "label": "Time read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval]) / rate(node_disk_reads_completed_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval]) / rate(node_disk_writes_completed_total{group_name=~\"$deployment_label\",instance_name=~\"$instance_name\"}[$interval])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  }
 ]
}