{
 "title": "SODALITE-PBS-EXPORTERS",
 "description": "Dashboard for the prometheus hpc exporters [PBS]",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "deployment_label",
    "label": "Deployment Label",
    "query": "label_values(pbs_queue_enabled, deployment_label)"
   },
   {
    "name": "job_id",
    "label": "Job ID",
    "query": "label_values(pbs_job_state{deployment_label=~\"$deployment_label\"}, job_id)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(pbs_queue_enabled{deployment_label=~\"$deployment_label\"},queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global info (associated deployment)，Deployment：$deployment_label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Job information【Deployment：$deployment_label】",
   "type": "table-old",
   "description": "Job information of the jobs selected for monitoring.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pbs_job_cpu_n{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "ncpus"
    },
    {
     "expr": "pbs_job_state{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "state"
    },
    {
     "expr": "pbs_job_priority{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "priority"
    },
    {
     "expr": "pbs_job_walltime_used{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "walltime used"
    },
    {
     "expr": "pbs_job_walltime_used{deployment_label=~\"$deployment_label\"}*100/pbs_job_walltime_max{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "% walltime used"
    },
    {
     "expr": "pbs_job_time_queued{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "time queued"
    },
    {
     "expr": "pbs_job_mem_virtual{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "vmem"
    },
    {
     "expr": "pbs_job_memory_physical{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "pmem"
    },
    {
     "expr": "pbs_job_exit_status{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "exit"
    }
   ]
  },
  {
   "title": "Queue information【Deployment：$deployment_label】",
   "type": "table-old",
   "description": "Queue information.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pbs_queue_enabled{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "enabled"
    },
    {
     "expr": "pbs_queue_started{deployment_label=~\"$deployment_label\"}-0",
     "legendFormat": "started"
    },
    {
     "expr": "pbs_queue_jobs_max{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_total{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_queued{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_running{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_held{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_waiting{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_transit{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_exiting{deployment_label=~\"$deployment_label\"}-0"
    },
    {
     "expr": "pbs_queue_jobs_complete{deployment_label=~\"$deployment_label\"}-0"
    }
   ]
  },
  {
   "title": "Job info (associated deployment)，Job ID：$job_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Job State",
   "type": "graph",
   "description": "0:Completed\n1:Exiting\n2:Running\n3:Queued\n4:Waiting\n5:Held\n6:Moving\n7:Suspended ",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_job_state{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pbs_job_mem_virtual{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pbs_job_memory_physical{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Job walltime used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pbs_job_walltime_used{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}/pbs_job_walltime_max{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    },
    {}
   ]
  },
  {
   "title": "Queued time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pbs_job_time_queued{deployment_label=~\"$deployment_label\",job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "Queue info (associated deployment)，Queue：$queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Queue state",
   "type": "graph",
   "description": "State of the selected queue",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_enabled{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Enabled"
    },
    {
     "expr": "pbs_queue_started{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Jobs submitted to queue: $queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_jobs_queued{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbs_queue_jobs_waiting{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "pbs_queue_jobs_running{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbs_queue_jobs_transit{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Transit"
    },
    {
     "expr": "pbs_queue_jobs_held{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbs_queue_jobs_exiting{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "(pbs_queue_jobs_max{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}+abs(pbs_queue_jobs_max{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}))/2*(1-pbs_queue_jobs_total{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}/pbs_queue_jobs_max{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "pbs_queue_jobs_complete{deployment_label=~\"$deployment_label\",queue_name=~\"$queue\"}",
     "legendFormat": "Complete"
    }
   ]
  }
 ]
}