{
 "title": "SODALITE-HPC-EXPORTERS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "consul-registered-hpc-exporters"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "job_id",
    "label": "HPC JOB-ID",
    "query": "label_values(pbs_qstat_u_jobstate{job=~\"$job\",instance=~\"$instance\"}, job_id)"
   },
   {
    "name": "job_name",
    "label": "HPC JOB-NAME:",
    "query": "label_values(pbs_qstat_u_jobstate{job=~\"$job\",instance=~\"$instance\"}, job_name)"
   },
   {
    "name": "username",
    "label": "HPC JOBS-USERNAME:",
    "query": "label_values(pbs_qstat_u_jobstate{job=~\"$job\",instance=~\"$instance\"}, username)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HPC JOBS",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pbs_qstat_u_totalruntime{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "consumedcputime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_qstat_u_consumedcputime{job=~\"$job\",instance=~\"$instance\",job_id=~\"$job_id\",job_name=~\"$job_name\",username=~\"$username\"}",
     "legendFormat": "ID:{{job_id}}-JOBNAME{{job_name}}-USER:{{username}}"
    }
   ]
  },
  {
   "title": "consumedpmem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_qstat_u_consumedpmem{job=~\"$job\",instance=~\"$instance\",job_id=~\"$job_id\",job_name=~\"$job_name\",username=~\"$username\"}",
     "legendFormat": "ID:{{job_id}}-JOBNAME{{job_name}}-USER:{{username}}"
    }
   ]
  },
  {
   "title": "consumedvmem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_qstat_u_consumedvmem{job=~\"$job\",instance=~\"$instance\",job_id=~\"$job_id\",job_name=~\"$job_name\",username=~\"$username\"}",
     "legendFormat": "ID:{{job_id}}-JOBNAME{{job_name}}-USER:{{username}}"
    }
   ]
  },
  {
   "title": "consumedwalltime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_qstat_u_consumedwalltime{job=~\"$job\",instance=~\"$instance\",job_id=~\"$job_id\",job_name=~\"$job_name\",username=~\"$username\"}",
     "legendFormat": "ID:{{job_id}}-JOBNAME{{job_name}}-USER:{{username}}"
    }
   ]
  },
  {
   "title": "exitstatus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_qstat_u_exitstatus{job=~\"$job\",instance=~\"$instance\",job_id=~\"$job_id\",job_name=~\"$job_name\",username=~\"$username\"}",
     "legendFormat": "ID:{{job_id}}-JOBNAME{{job_name}}-USER:{{username}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(promhttp_metric_handler_requests_total{code=\"200\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 200"
    },
    {
     "expr": "delta(promhttp_metric_handler_requests_total{code=\"500\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 500"
    },
    {
     "expr": "delta(promhttp_metric_handler_requests_total{code=\"503\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 503"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 200"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"500\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 500"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"503\",job=~\"$job\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "HTTP 503"
    }
   ]
  }
 ]
}