apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: sodalite-services
spec:
  commonName: keycloak.public-testbed.sodalite.eu
  secretName: keycloak-cert
  dnsNames:
    - keycloak.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
