---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  namespace: sodalite-services
  labels:
    app.kubernetes.io/name: keycloak
spec:
  containers:
  - name: keycloak
    image: jboss/keycloak
    resources:
      limits:
        cpu: "1"
        memory: "512M"
      requests:
        cpu: "0.5"
        memory: "512M"
    volumeMounts:
      - name: keycloak-secret
        mountPath: "/home/secret/"
        readOnly: true
    ports:
    - containerPort: 8080
    - containerPort: 8443
    env:
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_IMPORT
        value: /home/secret/sodalite-realm.json
  volumes:
    - name: keycloak-secret
      secret:
        secretName: keycloak-secret
        items:
          - key: sodalite-realm.json
            path: sodalite-realm.json
            mode: 0400