apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-based-refactorer
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: rule-based-refactorer
  replicas: 1
  template:
    metadata:
      labels:
        app: rule-based-refactorer
    spec:
      containers:
      - image: sodaliteh2020/rule_based_refactorer:latest
        imagePullPolicy: Always
        name: rule-based-refactorer
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: prometheus
            value: https://prometheus.public-testbed.sodalite.eu/
          - name: xopera
            value: https://xopera-rest-api.public-testbed.sodalite.eu/
          - name: refacopdiscoverer
            value: https://refactoring-option-discoverer.public-testbed.sodalite.eu
          - name: perfpredictor
            value: http://fo_perf_predictor_api:5000
          - name: forecaster
            value: http://forecast-api:5000
          - name: reasoner
            value: https://semantic-web.public-testbed.sodalite.eu/reasoner-api/v0.6/
          - name: authapi
            value: https://keycloak.public-testbed.sodalite.eu
          - name: iacbuilder
            value: https://iac-builder.public-testbed.sodalite.eu/
          - name: username
            value: indika
          - name: client_id
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: client-id
          - name: client_secret
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: client-secret
          - name: password
            valueFrom:
              secretKeyRef:
                name: rule-based-refactorer
                key: password
          - name: apikey
            value: test
          - name: graphdb
            value: https://knowledge-db.public-testbed.sodalite.eu/
          - name: pdsUri
            value: http://pds_api:5000/
          - name: refactorer
            value: https://rule-based-refactorer.public-testbed.sodalite.eu/rule-based-refactorer/v0.1/api/
       