apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret-uploader
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: vault-secret-uploader
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-secret-uploader
    spec:
      containers:
      - image: sodaliteh2020/iac-blueprint-builder
        name: vault-secret-uploader
        env:
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: introspect-url
        - name: OIDC_INTROSPECTION_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-secret
        - name: VAULT_ADDRESS
          value: "vault:8200"
        - name: VAULT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        - name: VAULT_SECRET_UPLOADER_PORT
          value: "8202"
        ports:
        - containerPort: 8202
          protocol: TCP
 
