tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/openstack/openstack_vm.yaml
  - modules/docker/docker_host.yaml
  - modules/docker/docker_network.yaml
  - modules/docker/docker_registry.yaml
  - modules/docker/docker_component.yaml
  - modules/docker/docker_certificate.yaml
  - modules/sodalite/types.yaml

topology_template:

  inputs:  
    docker-registry-ip:  
      type: string 
    ssh-key-name:  
      type: string 
    image-name:  
      type: string 
    openstack-network-name:  
      type: string 
    security-groups:  
      type: string    
    flavor-name:  
      type: string                   
    docker-network: 
      type: string
    dockerhub-user:
      type: string
      default: ""      
    dockerhub-pass: 
      type: string
      default: "" 
    docker-public-registry-url: 
      type: string
      default: ""
    docker-private-registry-url: 
      type: string
      default: ""
    docker-registry-cert-country-name:
      type: string
      default: ""
    docker-registry-cert-organization-name: 
      type: string
      default: ""
    docker-registry-cert-email-address: 
      type: string
      default: ""
    postgres_env:
      type: map
    xopera_env:
      type: map
    image_builder_env:
      type: map  

    prometheus_os_auth_url: 
      type: string
    prometheus_os_username: 
      type: string
    prometheus_os_password: 
      type: string
    prometheus_os_project_id:  
      type: string
    prometheus_os_project_name: 
      type: string

  node_templates: 

    security-rules-sodalite:  
      type: sodalite.nodes.OpenStack.SecurityRules 
      properties:  
        ports:  
          prometheus:  
            port_range_max: 9090 
            remote_ip_prefix: 0.0.0.0/0 
            port_range_min: 9090 
            protocol: tcp 
          component_ports:  
            port_range_max: 8085 
            remote_ip_prefix: 0.0.0.0/0 
            port_range_min: 8080 
            protocol: tcp 
          http_port:  
            port_range_min: 80 
            port_range_max: 80 
            protocol: tcp 
            remote_ip_prefix: 0.0.0.0/0 
          5000_ports:  
            port_range_min: 5000
            port_range_max: 5007
            protocol: tcp 
            remote_ip_prefix: 0.0.0.0/0
          https_port:
            port_range_min: 443
            port_range_max: 444
            protocol: tcp
            remote_ip_prefix: 0.0.0.0/0            
        group_name:  sodalite-uc 
        group_description:  Sodalite UC security group     

    sodalite-vm:  
      type: sodalite.nodes.OpenStack.VM 
      properties:  
        name:  sodalite-demo
        key_name:         { get_input: ssh-key-name } 
        image:            { get_input: image-name }
        network:          { get_input: openstack-network-name } 
        security_groups:  { get_input: security-groups } 
        flavor:           { get_input: flavor-name }
        username: centos
      requirements:  
        - protected_by: security-rules-sodalite 

    docker-host:
      type: sodalite.nodes.DockerHost
      requirements:
        - host: sodalite-vm

    docker-network:
      type: sodalite.nodes.DockerNetwork
      properties:  
        name: { get_input: docker-network }
      requirements:
        - host: sodalite-vm 
        - dependency: docker-host    
        
    docker-public-registry:
      type: sodalite.nodes.DockerRegistry
      properties:  
        docker_registry_url: { get_input: docker-public-registry-url } 
      requirements:
        - host: sodalite-vm
        - dependency: docker-host 

    docker-registry-certificate:
      type: sodalite.nodes.RegistryCertificate
      properties:  
        registry_ip:         { get_input: docker-private-registry-url }
        country_name:        { get_input: docker-registry-cert-country-name }
        organization_name:   { get_input: docker-registry-cert-organization-name }
        email_address:       { get_input: docker-registry-cert-email-address }
        cert_path: "/home/xopera/certs/"
        cert_files_prefix: "image.docker.local"
      requirements:
        - host: sodalite-vm 
        - dependency: docker-host        

    # monitoring-system
    # https://github.com/SODALITE-EU/monitoring-system
    prometheus-config:
      type: sodalite.nodes.Configuration.Prometheus
      properties:  
        os_auth_url:         { get_input: prometheus_os_auth_url }
        os_username:         { get_input: prometheus_os_username }
        os_password:         { get_input: prometheus_os_password }
        os_project_id:       { get_input: prometheus_os_project_id }
        os_project_name:     { get_input: prometheus_os_project_name }
        dir: /tmp/prometheus/
        filename: prometheus.yml
        skydive_connector_address: prometheus-skydive-connector:9100
      requirements:
        - host: sodalite-vm 
        - dependency: prometheus-skydive-connector
     
    prometheus-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: prometheus
        image_name: prom/prometheus:latest
        restart_policy: always
        ports:  ['9090:9090']
        exposed_ports:  ['9090']
        docker_network_name:  { get_property: [ SELF, network, name ] }
        volumes:
          - "/tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      requirements:
        - host: docker-host
        - registry: docker-public-registry  
        - network: docker-network         
    
    # xopera-rest-api
    # https://github.com/SODALITE-EU/xopera-rest-api        
    xopera-openstack-keys:
      type: sodalite.nodes.ConfigureKeys
      requirements:
        - host: sodalite-vm

    xopera-postgres-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name: library/postgres:13
        volumes:
          - "/home/postgres:/var/lib/postgresql/data"
        ports: ['5432:5432']
        alias: xopera-postgres
        env: { get_input: postgres_env }
        docker_network_name:  { get_property: [ SELF, network, name ] }
      requirements:
        - host:  docker-host
        - network: docker-network
        - registry: docker-public-registry 

    xopera-flask-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: xopera-flask
        docker_network_name:  { get_property: [ SELF, network, name ] }
        image_name: sodaliteh2020/xopera-flask:M18Release
        restart_policy: always
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/root/.ssh/:/root/.ssh/"
          - "/home/xopera/certs:/home/xopera/certs"
        exposed_ports:  ['5000']
        env: { get_input: xopera_env }
      requirements:
        - host: docker-host
        - registry: docker-public-registry  
        - network: docker-network 
        - dependency: xopera-openstack-keys
        - dependency: xopera-postgres-container
        - dependency: docker-registry-certificate

    xopera-nginx-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: xopera-nginx
        docker_network_name:  { get_property: [ SELF, network, name ] }
        image_name: sodaliteh2020/xopera-nginx:M18Release
        restart_policy: always
        ports:  ['5001:443', '5000:80']
        #exposed_ports:  ['443', '5000']
        volumes:
          - "/home/xopera/certs:/etc/nginx/certs"
      requirements:
        - host: docker-host
        - registry: docker-public-registry   
        - network: docker-network           
        - dependency: xopera-flask-container
        - dependency: docker-registry-certificate

    # iac-blueprint-builder 
    # https://github.com/SODALITE-EU/iac-blueprint-builder 
    iac-builder-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: iac-builder
        image_name: sodaliteh2020/iac-blueprint-builder:24
        docker_network_name:  { get_property: [ SELF, network, name ] }
        restart_policy: always
        ports: 
        - "8081:80"
        env:
          XOPERA_ENDPOINT: http://xopera-nginx:80
      requirements:
        - host: docker-host
        - registry: docker-public-registry 
        - network: docker-network    
        - dependency: xopera-nginx-container

    # image-builder     
    # https://github.com/SODALITE-EU/image-builder  
    image-builder-flask:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name:  sodaliteh2020/image-builder-flask:v0.2.1
        docker_network_name:  { get_property: [ SELF, network, name ] }
        exposed_ports:  ['5000']
        env: { get_input: image_builder_env }
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        alias: image-builder-flask
      requirements:
        - host:  docker-host
        - registry: docker-public-registry 
        - network: docker-network

    image-builder-nginx:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name: sodaliteh2020/image-builder-nginx:v0.2.1
        docker_network_name:  { get_property: [ SELF, network, name ] }
        ports:  ['5002:443']
        #exposed_ports:  ['443']
        volumes:
          - "/home/xopera/certs:/etc/nginx/certs"
        alias: image-builder-nginx
      requirements:
        - host:  docker-host
        - dependency: image-builder-flask
        - network: docker-network 
        - registry: docker-public-registry 
        - dependency: docker-registry-certificate

    # semantic-reasoner     
    # https://github.com/SODALITE-EU/semantic-reasoner 
    know-db-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: graph-db
        docker_network_name:  { get_property: [ SELF, network, name ] }
        image_name: sodaliteh2020/graph_db:172
        restart_policy: always
        ports:  ['7200:7200']
        exposed_ports:  ['7200']
      requirements:
        - host: docker-host
        - registry: docker-public-registry   
        - network: docker-network      

    semantic-web-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: semantic-web
        docker_network_name:  { get_property: [ SELF, network, name ] }
        image_name: sodaliteh2020/semantic_web:172
        restart_policy: always
        env:
          WAIT_HOSTS: graph-db:7200
          environment: docker
          graphdb:  http://graph-db:7200
          bugPredictorServer:  http://tosca-smells:8080/  
          ansiblePath: /usr/local/tomcat/webapps/Ansibles/
          reasonerServer: http://semantic-web:8080/
        ports:  ['8080:8080']
        volumes:
          - "/tmp/tomcat/webapps/Ansibles:/usr/local/tomcat/webapps/Ansibles"   
      requirements:
        - host: docker-host
        - registry: docker-public-registry   
        - network: docker-network     
        - dependency: know-db-container
        - dependency: tosca-smells-container

    # iac-quality-framework   
    # https://github.com/SODALITE-EU/iac-quality-framework
    iac-metrics-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: iac-metrics
        image_name: sodaliteh2020/iacmetrics:8
        restart_policy: always
        ports:  ['5003:5000']
      requirements:
        - host: docker-host
        - registry: docker-public-registry   
     
    # defect-prediction      
    # https://github.com/SODALITE-EU/defect-prediction         
    tosca-smells-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: tosca-smells
        docker_network_name:  { get_property: [ SELF, network, name ] }
        image_name: sodaliteh2020/toscasmells:124
        restart_policy: always
        env:
          environment: docker
          WAIT_HOSTS: graph-db:7200
          graphdb: http://graph-db:7200
        ports:  ['8082:8080']
        exposed_ports:  ['8080']
      requirements:
        - host: docker-host
        - registry: docker-public-registry  
        - dependency: know-db-container
        - network: docker-network 

    ansible-smells-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: ansible-smells
        image_name: sodaliteh2020/ansiblesmells:124
        restart_policy: always
        ports:  ['5004:5000']
      requirements:
        - host: docker-host
        - registry: docker-public-registry          

    # verification    
    # https://github.com/SODALITE-EU/verification 
    tosca-syntax-verifier-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: tosca-syntax
        image_name: sodaliteh2020/toscasynverifier:8
        restart_policy: always
        ports:  ['5005:5000']
      requirements:
        - host: docker-host
        - registry: docker-public-registry           

    workflow-verifier-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: workflow-verifier
        image_name: sodaliteh2020/workflowverifier:8
        restart_policy: always
        ports:  ['5006:5000']
      requirements:
        - host: docker-host
        - registry: docker-public-registry         
    # refactoring-ml
    # https://github.com/SODALITE-EU/refactoring-ml      
    rule-based-refactorer-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: rule-based-refactorer
        image_name: sodaliteh2020/rule_based_refactorer:49
        restart_policy: always
        ports:  ['8083:8080']
        docker_network_name:  { get_property: [ SELF, network, name ] }
        env:
          prometheus: http://prometheus:9090
          xopera: http://xopera-nginx:5000
          refacopdiscoverer: http://refactoring-option-discoverer:8080
          perfpredictor: http://performance-predictor-refactoring:5000
      requirements:
        - host: docker-host
        - registry: docker-public-registry 
        - network: docker-network   
        - dependency: xopera-nginx-container
        - dependency: performance-predictor-refactoring-container
        - dependency: refactoring-option-discoverer-container
        
    performance-predictor-refactoring-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: performance-predictor-refactoring
        image_name: sodaliteh2020/fo_perf_predictor_api:49
        restart_policy: always
        ports:  ['5007:5000']
        docker_network_name:  { get_property: [ SELF, network, name ] }
        env:
          prometheus: http://prometheus:9090
          xopera: http://xopera-nginx:5000
          refacopdiscoverer: http://refactoring-option-discoverer:8080
          perfpredictor: http://performance-predictor-refactoring:5000
      requirements:
        - host: docker-host
        - registry: docker-public-registry 
        - network: docker-network  
        - dependency: xopera-nginx-container
        - dependency: refactoring-option-discoverer-container

    # https://github.com/SODALITE-EU/refactoring-option-discoverer
    refactoring-option-discoverer-container:
      type: sodalite.nodes.DockerizedComponent
      properties:
        alias: refactoring-option-discoverer
        image_name: sodaliteh2020/refactoring_option_discoverer:60
        restart_policy: always
        ports:  ['8084:8080']
        env:
          graphdb: http://graph-db:7200
        docker_network_name:  { get_property: [ SELF, network, name ] }
      requirements:
        - host: docker-host
        - registry: docker-public-registry  
        - network: docker-network         
        - dependency: know-db-container        

    # skydive-analyzer
    # https://github.com/skydive-project/skydive
    skydive-analyzer:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name:  skydive/skydive
        command: analyzer
        docker_network_name:  { get_property: [ SELF, network, name ] }
        ports:  ['8088:8082', '8088:8082/udp']
        alias: skydive-analyzer
      requirements:
        - host:  docker-host
        - registry: docker-public-registry
        - network: docker-network

    # skydive-capture
    # https://github.com/skydive-project/skydive
    skydive-capture:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name:  skydive/skydive
        command: client capture create --extra-tcp-metric --gremlin "G.V()"
        docker_network_name:  { get_property: [ SELF, network, name ] }
        env:
          SKYDIVE_ANALYZERS: skydive-analyzer:8082
        alias: skydive-capture
      requirements:
        - host:  docker-host
        - registry: docker-public-registry
        - network: docker-network
        - dependency: skydive-analyzer

    # prometheus-skydive-connector
    # https://github.com/SODALITE-EU/skydive-flow-exporter/prom_sky_con
    prometheus-skydive-connector:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name: sodaliteh2020/prometheus-skydive-connector
        command: /etc/prom_sky_con.yml
        docker_network_name:  { get_property: [ SELF, network, name ] }
        env:
          SKYDIVE_PIPELINE_SUBSCRIBER_URL="ws://skydive-analyzer:8082/ws/subscriber/flow"
        ports:  ['9101:9100']
        alias: prometheus-skydive-connector
      requirements:
        - host:  docker-host
        - registry: docker-public-registry
        - network: docker-network

