apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-exporter
  namespace: sodalite-services
spec:
  selector:
    matchLabels:
      app: hpc-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: hpc-exporter
    spec:
      containers:
      - image: sodaliteh2020/hpc-exporter
        name: hpc-exporter
        env:
        - name: OIDC_INTROSPECTION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: introspect-url
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: client-secret
        - name: VAULT_SECRET_UPLOADER_ADDRESS
          value: vault-secret-uploader:8202
        ports:
        - containerPort: 9110
          protocol: TCP
 
