apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iac-builder-cert
  namespace: sodalite-services
spec:
  commonName: iac-builder.public-testbed.sodalite.eu
  secretName: iac-builder-cert
  dnsNames:
    - iac-builder.public-testbed.sodalite.eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
